apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: glpi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path   ***REMOVED*** k3s default storage class
  resources:
    requests:
      storage: 5Gi
