apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-dev
  namespace: website-dev
  annotations:
    ***REMOVED*** Traefik (k3s default ingress controller)
    ***REMOVED*** SSL термінується на домашньому Nginx proxy, тут plain HTTP
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: dev.k8s.YOUR_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-dev
                port:
                  number: 80
